# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{donkey}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Howard Yeh"]
  s.date = %q{2009-11-30}
  s.email = %q{hayeah@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION.yml",
     "lib/ass.rb",
     "lib/ass/actor.rb",
     "lib/ass/amqp.rb",
     "lib/ass/callback_factory.rb",
     "lib/ass/client.rb",
     "lib/ass/peeper.rb",
     "lib/ass/rpc.rb",
     "lib/ass/serializers.rb",
     "lib/ass/server.rb",
     "lib/ass/topic.rb",
     "test/ass_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/hayeah/donkey}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Asynchronous Service Stages for Distributed Services}
  s.test_files = [
    "spec/ass_spec.rb",
     "spec/client_spec.rb",
     "spec/actor_spec.rb",
     "spec/rpc_spec.rb",
     "test/ass_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amqp>, [">= 0"])
    else
      s.add_dependency(%q<amqp>, [">= 0"])
    end
  else
    s.add_dependency(%q<amqp>, [">= 0"])
  end
end

